### PR TITLE
ensure router has correct mapping and fix a respond data type

### PR DESCRIPTION
**Pull request by euniceatcouchbase**
in router.cs, fixed a wrong mapping, and added a new mapping.
in ReplicationMethods.ca, corrected a respond data type.

### CODE REVIEW

**Review by sridevi-15 — APPROVED** [review]
Eunice, there are test server app changes. As soon ass it is merged, can you have test sesrver app built on jenkins and. have sanity run and see .net is not effected

**Comment by euniceatcouchbase** [comment]
I am not sure if testserver app suppose to be built from master or from Manasa's working branch. @mgcouchbase could you merge this change into your branch once it gets approved and gets into master?

**Comment by mgcouchbase** [comment]
I will pull these changes into my branch and commit .

**Review by mgcouchbase — APPROVED** [review]

**Comment by euniceatcouchbase** [comment]
super! thanks a lot!

**Pull request merged**
